config/routes.rb
Shop::Application.routes.draw do

  resources :line_items

  resources :carts

  get "store/index"

  resources :updates

  resources :infos

  root :to => "store#index" , :as => 'store'
  
  resources :products	do
	  resources :updates
  end
  

end

app/models/update.rb
class Update < ActiveRecord::Base
  attr_accessible :description, :effective_date, :product_id, :purchase_date, :unit, :unit_price, :name
  
  belongs_to :product
  
   
  def product_should_be_published 
    errors.add(:product_id, "is not published yet") if product && !product.published? 
  end   
  
  
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
  
    before_filter :load_product 
 
  def create 
    @update = @product.updates.new(params[:update]) 
    if @update.save 
      redirect_to @product, :notice => 'Thanks for your update' 
    else 
      redirect_to @product, :alert => 'Unable to add update' 
    end 
  end 
   
  def destroy 
    @update = @product.updates.find(params[:id]) 
    @update.destroy 
    redirect_to @product, :notice => 'update deleted' 
  end 
   
  private 
    def load_product 
      @product = Product.find(params[:product_id]) 
    end 
  
 
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/views/updates/_form.html.erb
<%= form_for(@update) do |f| %>
  <% if @update.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@update.errors.count, "error") %> prohibited this update from being saved:</h2>

      <ul>
      <% @update.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :unit %><br />
    <%= f.text_field :unit %>
  </div>
  <div class="field">
    <%= f.label :unit_price %><br />
    <%= f.text_field :unit_price %>
  </div>
  <div class="field">
    <%= f.label :effective_date %><br />
    <%= f.datetime_select :effective_date %>
  </div>
  <div class="field">
    <%= f.label :purchase_date %><br />
    <%= f.datetime_select :purchase_date %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/updates/_update.html.erb
<%= div_for update do %> 
  <h3> 
    &lt;<%= update.effective_date %>&gt; নতুন আপডেট: 
    <span class='actions'> 
      <%= link_to 'Delete', product_update_path(:product_id => @product,  
:id => update), :confirm => 'Are you sure?', :method => :delete %> 
    </span> 
  </h3> 
  <div><%= update.unit %></div> 
  <div><%= update.unit_price %> </div>
<div>  <%= update.effective_date %> </div>
<div>  <%= update.purchase_date %> </div>
<div>  <%= update.description %> </div>
<% end %> 

app/views/updates/edit.html.erb
<h1>Editing update</h1>

<%= render 'form' %>

<%= link_to 'Show', @update %> |
<%= link_to 'Back', updates_path %>

app/views/updates/index.html.erb
<h1>Listing updates</h1>

<table>
  <tr>
    <th>Product</th>
    <th>Unit</th>
    <th>Unit price</th>
    <th>Effective date</th>
    <th>Purchase date</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @updates.each do |update| %>
  <tr>
    <td><%= update.product_id %></td>
    <td><%= update.unit %></td>
    <td><%= update.unit_price %></td>
    <td><%= update.effective_date %></td>
    <td><%= update.purchase_date %></td>
    <td><%= update.description %></td>
    <td><%= link_to 'Show', update %></td>
    <td><%= link_to 'Edit', edit_update_path(update) %></td>
    <td><%= link_to 'Destroy', update, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Update', new_update_path %>

app/views/updates/new.html.erb
<%= form_for([@product, @product.updates.new]) do |f| %> 
  <div class="field"> 
    <%= f.label :unit %><br /> 
    <%= f.text_field :unit %> 
  </div> 
  <div class="field"> 
    <%= f.label :unit_price %><br /> 
    <%= f.text_field :unit_price %> 
  </div> 
  <div class="field"> 
    <%= f.label :effective_date %><br /> 
    <%= f.datetime_select :effective_date %> 
  </div> 
  <div class="field"> 
    <%= f.label :purchase_date %><br /> 
    <%= f.datetime_select :purchase_date %> 
  </div> 
  <div class="field"> 
    <%= f.label :description %><br /> 
    <%= f.text_area :unit %> 
  </div> 
  <div class="actions"> 
    <%= f.submit 'Add' %> 
  </div> 
<% end %> 

app/views/updates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @update.product_id %>
</p>

<p>
  <b>Unit:</b>
  <%= @update.unit %>
</p>

<p>
  <b>Unit price:</b>
  <%= @update.unit_price %>
</p>

<p>
  <b>Effective date:</b>
  <%= @update.effective_date %>
</p>

<p>
  <b>Purchase date:</b>
  <%= @update.purchase_date %>
</p>

<p>
  <b>Description:</b>
  <%= @update.description %>
</p>


<%= link_to 'Edit', edit_update_path(@update) %> |
<%= link_to 'Back', updates_path %>