config/routes.rb
Shop::Application.routes.draw do

  resources :line_items

  resources :carts

  get "store/index"

  resources :updates

  resources :infos

  root :to => "store#index" , :as => 'store'
  
  resources :products	do
	  resources :updates
  end
  

end

app/models/info.rb
class Info < ActiveRecord::Base
  attr_accessible :description, :effective_date, :product_id, :purchase_date, :unit, :unit_price
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  # GET /infos
  # GET /infos.json
  def index
    @infos = Info.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @infos }
    end
  end

  # GET /infos/1
  # GET /infos/1.json
  def show
    @info = Info.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @info }
    end
  end

  # GET /infos/new
  # GET /infos/new.json
  def new
    @info = Info.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @info }
    end
  end

  # GET /infos/1/edit
  def edit
    @info = Info.find(params[:id])
  end

  # POST /infos
  # POST /infos.json
  def create
    @info = Info.new(params[:info])

    respond_to do |format|
      if @info.save
        format.html { redirect_to @info, notice: 'Info was successfully created.' }
        format.json { render json: @info, status: :created, location: @info }
      else
        format.html { render action: "new" }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /infos/1
  # PUT /infos/1.json
  def update
    @info = Info.find(params[:id])

    respond_to do |format|
      if @info.update_attributes(params[:info])
        format.html { redirect_to @info, notice: 'Info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infos/1
  # DELETE /infos/1.json
  def destroy
    @info = Info.find(params[:id])
    @info.destroy

    respond_to do |format|
      format.html { redirect_to infos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/views/infos/_form.html.erb
<%= form_for(@info) do |f| %>
  <% if @info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@info.errors.count, "error") %> prohibited this info from being saved:</h2>

      <ul>
      <% @info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :unit %><br />
    <%= f.text_field :unit %>
  </div>
  <div class="field">
    <%= f.label :unit_price %><br />
    <%= f.text_field :unit_price %>
  </div>
  <div class="field">
    <%= f.label :effective_date %><br />
    <%= f.datetime_select :effective_date %>
  </div>
  <div class="field">
    <%= f.label :purchase_date %><br />
    <%= f.datetime_select :purchase_date %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/infos/edit.html.erb
<h1>Editing info</h1>

<%= render 'form' %>

<%= link_to 'Show', @info %> |
<%= link_to 'Back', infos_path %>

app/views/infos/index.html.erb
<h1>Listing infos</h1>

<table>
  <tr>
    <th>Product</th>
    <th>Unit</th>
    <th>Unit price</th>
    <th>Effective date</th>
    <th>Purchase date</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @infos.each do |info| %>
  <tr>
    <td><%= info.product_id %></td>
    <td><%= info.unit %></td>
    <td><%= info.unit_price %></td>
    <td><%= info.effective_date %></td>
    <td><%= info.purchase_date %></td>
    <td><%= info.description %></td>
    <td><%= link_to 'Show', info %></td>
    <td><%= link_to 'Edit', edit_info_path(info) %></td>
    <td><%= link_to 'Destroy', info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Info', new_info_path %>

app/views/infos/new.html.erb
<h1>New info</h1>

<%= render 'form' %>

<%= link_to 'Back', infos_path %>

app/views/infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @info.product_id %>
</p>

<p>
  <b>Unit:</b>
  <%= @info.unit %>
</p>

<p>
  <b>Unit price:</b>
  <%= @info.unit_price %>
</p>

<p>
  <b>Effective date:</b>
  <%= @info.effective_date %>
</p>

<p>
  <b>Purchase date:</b>
  <%= @info.purchase_date %>
</p>

<p>
  <b>Description:</b>
  <%= @info.description %>
</p>


<%= link_to 'Edit', edit_info_path(@info) %> |
<%= link_to 'Back', infos_path %>